-- Generic event table for extensibility
CREATE TABLE IF NOT EXISTS fact_event (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL, -- e.g., 'habit', 'mood', 'music_session', 'custom', etc.
  event_time TIMESTAMP WITH TIME ZONE NOT NULL,
  user_id BIGINT,
  ref_id BIGINT, -- optional: reference to another fact/dim table
  payload JSONB, -- flexible event data
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  source TEXT
);
COMMENT ON TABLE fact_event IS 'Generic event log for all user/system events.';
CREATE INDEX IF NOT EXISTS idx_event_type_time ON fact_event(event_type, event_time);

-- Generic enrichment table for AI/ML output
CREATE TABLE IF NOT EXISTS fact_enrichment (
  enrichment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES fact_event(event_id) ON DELETE CASCADE,
  enrichment_type TEXT NOT NULL, -- e.g., 'sentiment', 'emotion', 'category', 'embedding', etc.
  enrichment_data JSONB, -- flexible AI/ML output
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  model_name TEXT,
  source TEXT
);
COMMENT ON TABLE fact_enrichment IS 'Stores AI/ML enrichments for any event.';
CREATE INDEX IF NOT EXISTS idx_enrichment_event_type ON fact_enrichment(event_id, enrichment_type);
--
-- [SCHEMA NOTE]
-- This DWH now uses a generic event/enrichment pattern:
--   - All user/system events are stored in fact_event (with event_type and flexible JSON payload)
--   - All AI/ML enrichments are stored in fact_enrichment (linked to event_id, with flexible JSONB)
-- Legacy fact tables (habits, mood, music_session) are now modeled as event_type values in fact_event.
-- See migration notes inline for payload structure examples.
-- Consolidated from tmp/*.sqlite fragments (dim and fact tables)
-- Adjusted for PostgreSQL: identity PKs, explicit foreign keys, and index creation

-- Dimension: date
CREATE TABLE IF NOT EXISTS dim_date (
  date_key BIGINT PRIMARY KEY,
  date TEXT NOT NULL
);
COMMENT ON TABLE dim_date IS 'Lookup table for calendar dates.';

-- Dimension: emotion
CREATE TABLE IF NOT EXISTS dim_emotion (
  emotion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  valence INTEGER NOT NULL,
  arousal INTEGER NOT NULL
);
COMMENT ON TABLE dim_emotion IS 'Normalized emotion taxonomy (Plutchik-style attributes).';

-- Dimension: location
CREATE TABLE IF NOT EXISTS dim_location (
  location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  kind TEXT
);
COMMENT ON TABLE dim_location IS 'Places or named locations used in entries.';

-- Dimension: album
CREATE TABLE IF NOT EXISTS dim_album (
  album_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  artist TEXT,
  format TEXT,
  year INTEGER,
  genre TEXT,
  source TEXT,
  location TEXT,
  notes TEXT
);
COMMENT ON TABLE dim_album IS 'Music album metadata.';

-- Dimension: audio device
CREATE TABLE IF NOT EXISTS dim_audio_device (
  device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT,
  brand TEXT,
  model TEXT,
  acquisition_date TEXT,
  purchase_price_mxn REAL,
  condition TEXT,
  location TEXT,
  notes TEXT
);
COMMENT ON TABLE dim_audio_device IS 'Describes audio equipment used for listening sessions.';


-- [MIGRATION NOTE] fact_habits is now modeled as fact_event with event_type='habit'.
-- Example payload: {"date_key": ..., "habit_type": ..., "description": ..., "impact_domain": ..., "value": ..., "unit": ..., "notes": ...}


-- [MIGRATION NOTE] fact_mood is now modeled as fact_event with event_type='mood'.
-- Example payload: {"date_key": ..., "dominant_emotion_id": ..., "mood_score": ..., "energy_level": ..., "stress_level": ..., "notes": ...}





COMMIT;